services:
  backend:
    build: ./myapp
    network_mode: "host" 
    privileged: true
    # 👇 ضيف الجزء ده عشان ندي للكونتينر صلاحيات الـ Sniffing
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - SOCKETCLUSTER_PORT=8000
    # لو عايز ترفع ملفات pcap وتتحفظ فعلاً:
    volumes:
      - ./myapp/uploads:/usr/src/app/uploads