[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/auth/*"
  to = "https://cyphernet-backend.onrender.com/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/users/*"
  to = "https://cyphernet-backend.onrender.com/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/rooms/*"
  to = "https://cyphernet-backend.onrender.com/rooms/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/messages/*"
  to = "https://cyphernet-backend.onrender.com/messages/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/files/*"
  to = "https://cyphernet-backend.onrender.com/files/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/orgs/*"
  to = "https://cyphernet-backend.onrender.com/orgs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ice-servers"
  to = "https://cyphernet-backend.onrender.com/ice-servers"
  status = 200
  force = true

[[redirects]]
  from = "/upload"
  to = "https://cyphernet-backend.onrender.com/upload"
  status = 200
  force = true
